### ISSUE TITLE
Multiple aggregator

### ISSUE THREAD

**Issue by nitinuttarwar** [nagarajanchinnasamy/pivottable-subtotal-renderer#11]
Can we use multiple aggregator in the subtotal rederer?

**Comment by nagarajanchinnasamy** [comment]
This is actually a question on core pivottable package. Please refer to Wiki at:

https://github.com/nicolaskruchten/pivottable/wiki/Aggregators

Look for `Pivot().aggregator`, `PivotUI().aggregators` and `PivotUI().aggregatorName`

Short answer is: No. You can only have one aggregator per pivot instance.

Could you please explain what is it that you are trying to achieve?
