### ISSUE TITLE
Give label for Subtotal

### ISSUE THREAD

**Issue by zam6ak** [nagarajanchinnasamy/pivottable-subtotal-renderer#14]
Is it possible to give a label for the subtotals row?

In your example:
http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivot.html

if you expand on Gender, the top cell for Procince (subtotal) is blank.
It would be nice if it could automatically put in "Subtotal for Province" 
Perhaps via config option or something....

**Comment by nagarajanchinnasamy** [comment]
@zam6ak If I am right, you are referring to the highlighted cell in the attached image.

Sure, we can add a title text instead of keeping it empty. I will take this as an enhancement.

Just one clarification though: That highlighted cell's row is the subtotal row for Female. Not for Province.
![subtotalrowheader](https://cloud.githubusercontent.com/assets/1784880/20032717/a500babc-a3b6-11e6-8a0a-8a2d59613e5c.png)

**Comment by zwirnerj** [comment]
@zam6ak maybe it helps if you just add: 
`table.pvtTable .pvtRowLabel {vertical-align: top;}`
to your css file. After that the "female" label is on top next to the subtotal.
There are a lot of things that can be done to fit your needs just by adjustment of CSS: 
![example](https://cloud.githubusercontent.com/assets/807691/20052129/d858b0b4-a4d2-11e6-92cc-9fecd7da447e.png)

**Comment by zam6ak** [comment]
@nagarajanchinnasamy You are correct, it is for Female. I think it would be nice to add this via config option and if enabled it would just put text "Totals for {{colOrRowName}}" Also, perhaps, this makes sense only when item is expanded?

@zwirnerj  this is not the same as having a label....I do think this CSS should be default though. It helps a lot

**Comment by nagarajanchinnasamy** [comment]
Thanks @zwirnerj ... Nice idea :)

Along with what @zwirnerj has suggested you can highlight the subtotal row with a different background color as shown in one of the examples. I think that will be more elegant without adding more text into the table.

@zam6ak  I get your point too.... Please try above suggestions and let us know. Implementation wise it should not be very difficult to add what you are suggesting... but would like to hear from you after you have tried the options suggested. Thanks :)

**Comment by zam6ak** [comment]
@nagarajanchinnasamy  I added teh style that @zwirnerj  suggested. It looks better, but I wish there was a way to change the background color of the subtotals row but only row when expanded.
I think that would ultimately do it.

**Comment by nagarajanchinnasamy** [comment]
Did you check this the example at: 

http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivot_css.html

Does that help?

**Comment by ilyaguy** [comment]
I've used following styles
```
            table.pvtTable .pvtRowLabel {vertical-align: top;}
            .pvtRowSubtotal.rowcol0, .pvtColSubtotal.colcol0 {
                background-color: #EFEFEF !important;
                font-size: 1.3em;
                font-weight:bold;
            }
            .pvtRowSubtotal.rowcol1, .pvtColSubtotal.colcol1 {
                background-color: #EFEFEF !important;
                font-size: 1.2em;
                font-weight:bold;
            }
            .pvtRowSubtotal.rowcol2, .pvtColSubtotal.colcol2 {
                background-color: #EFEFEF !important;
                font-size: 1.1em;
                font-weight:bold;
            }
            .pvtRowSubtotal {
                background-color: #EFEFEF !important;
                font-weight:bold;
            }

```
and result is:
<img width="329" alt="screen shot 2016-11-18 at 01 30 02" src="https://cloud.githubusercontent.com/assets/6704355/20412343/c6d73e50-ad2e-11e6-9d70-468e995f6341.png">

**Comment by zam6ak** [comment]
@ilyaguy  After applying your styles I realized that background color completely wipes out effects of Heatmap renderer....

**Comment by nagarajanchinnasamy** [comment]
@zam6ak hope `styling collapsable labels #20` will be able to meet your requirement!!!???

**Comment by nagarajanchinnasamy** [comment]
Will take this forward with #20 `styling collapsible labels`. Closing this for now.
