### ISSUE TITLE
Default collapse behaviour

### ISSUE THREAD

**Issue by ilyaguy** [nagarajanchinnasamy/pivottable-subtotal-renderer#17]
At first, thank you for the plugin.

Then question: could you suggest how I can change default collapse behaviour? 

I want to collapse all rows without describing attributes in `rendererOptions { collapseRowsAt: [] }`.

**Comment by nagarajanchinnasamy** [comment]
Hi, Welcome :)

Just want to understand the reason behind not being able to mention one of the values of `rows` array as the value for `collapseRowsAt` so that I can think of a right solution for this.

**Comment by ilyaguy** [comment]
I use PivotUI, and person, who use the report, can change the settings of pivot table, so `collapseRowsAt` settings will work only in default case.

**Comment by nagarajanchinnasamy** [comment]
Do you basically mean, it cant be declarative??? And you want an API to be called at runtime???

**Comment by ilyaguy** [comment]
If you open your [example](http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivotui.html) and exchange "Party" and "Gender" (Drag "Party" to the rows and "Gender" to the columns) then all subtotals will expands and grid will become too big.

My idea is: subtotals blocks should be collapsed by default.
So, if you drag "Province", "Party" and "Gender" to rows, all of them will be collapsed and user will see only province list.
And the same behaviour is acceptable for columns too.

I don't need an API to change `collapseRowsAt` at runtime, configuration options like `alwaysCollapseRows` and `alwaysCollapseCols` should be enough.

**Comment by nagarajanchinnasamy** [comment]
How about mentioning the index/position instead of a row/column attribute name so that it works always at a level rather than by a specific attribute name?

`collapseRowsAt: 0` will collapse all rows at first level irrespective of what the first element is in `rows` array.

Does that sound alright?

**Comment by ilyaguy** [comment]
It looks like good idea.

**Comment by nagarajanchinnasamy** [comment]
@ilyaguy I have committed the changes to master branch. Added `subtotal_pivotui_collapse_numeric.html` to examples. Please check and let me know if everything is fine. We can make a release with this feature. Thanks for your participation and feedback.

**Comment by ilyaguy** [comment]
@nagarajanchinnasamy It works fine! Thank you.
