### ISSUE TITLE
Empty filter lead to JS error.

### ISSUE THREAD

**Issue by ilyaguy** [nagarajanchinnasamy/pivottable-subtotal-renderer#19]
If you clear any filter, renderer lead to JS error:
```
pivot.coffee:551 TypeError: Cannot read property 'length' of undefined
    at processKeys (subtotal.coffee:84)
    at main (subtotal.coffee:591)
    at SubtotalRenderer (subtotal.coffee:638)
    at Object.Table With Subtotal [as renderer] (subtotal.coffee:641)
    at m.t.fn.pivot (pivot.coffee:549)
    at pivot.coffee:838
```

**Comment by nagarajanchinnasamy** [comment]
Thanks for the feedback. Please give more details. I couldn't understand what you mean by "if you clear any filter'!!!

**Comment by ilyaguy** [comment]
1.  Open, for example, http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivotui.html
2. Double click on "Gender".
3. Unselect both elements ("Male", "Female").
4. Click "OK"

**Comment by nagarajanchinnasamy** [comment]
Thanks. Understood :) This got to be a bug!!!!

Will revert asap.

**Comment by nagarajanchinnasamy** [comment]
@ilyaguy I have committed the changes to master branch. Currently when  emptying filters for any of row or column attributes will result in an empty table. I have checked that the base `pivottable.js` examples also behave the same way.

Please verify the fix and confirm.... Thanks :)

**Comment by ilyaguy** [comment]
It works correct. Thank you.

**Comment by ilyaguy** [comment]
You didn't push the fix to examples site. :)

**Comment by nagarajanchinnasamy** [comment]
Yes...I do that after making the release... Its yet to be released :)
