### ISSUE TITLE
styling collapsable labels

### ISSUE THREAD

**Issue by zam6ak** [nagarajanchinnasamy/pivottable-subtotal-renderer#20]
I would like to add `cursor: pointer` to row and column labels that are collapsible.
But classes alone do not differentiate between collapsible vs non-collapsible columns and rows.
At least not that I can see (e.g. classes `pvtRowLabel` and `pvtAxisLabel`)

Is there a way to accomplish this?

**Comment by nagarajanchinnasamy** [comment]
@zam6ak Thanks for your feedback :)

One of `expanded` and`collapsed` classes is added to headers and labels based on their current status. Changes regarding this are committed to master.

Please check and confirm if the changes are fine.

**Comment by nagarajanchinnasamy** [comment]
Feature incorporated into Version 1.1.1

**Comment by zam6ak** [comment]
@nagarajanchinnasamy I think the label should be wrapped in span element and then that span should be either collapsed or expanded. Right now, on tall columns, entire cell is click-able (with pointer: cursor).
Unless that was by design....Is it? (meaning if I vertically align to top a collapsible, tall column - should clicking anywhere in that cell expand it or just when clicking on the table)?

**Comment by zam6ak** [comment]
@nagarajanchinnasamy  Also, may be usefull to add some notes to new CSS file about interference with Heatmap renderer...This is what I have:

```
table.pvtTable .collapsed,  table.pvtTable .expanded {
    cursor: pointer
}

/* applying following styles interferes with Heatmap renderer */
/*
table.pvtTable .pvtRowSubtotal {
    background-color: #efefef !important;
    font-weight: bold;
}

table.pvtTable .pvtColSubtotal {
    background-color: #efefef !important;
    font-weight: bold;
}
*/
```

**Comment by nagarajanchinnasamy** [comment]
@zam6ak Thanks for the feedback.

Yes I deliberately left the whole cell clickable so that users don;t have to exactly place the mouse on the label to click. Hope that;s more convenient!!!

Also I will add the notes to CSS on interference with heatmap renderer. Thanks :)
