### ISSUE TITLE
Drilldown callback

### ISSUE THREAD

**Issue by dave-killough** [nagarajanchinnasamy/pivottable-subtotal-renderer#21]
Great job!   Nicolas just added drilldown support to his built-in table.  Would you be willing to add this feature to subtotal as well?  Thanks.

**Comment by nagarajanchinnasamy** [comment]
Thanks for your feedback. Could you please point me to an example to understand how this works.

**Comment by dave-killough** [comment]
Here's the example Nicolas provided on his site.  Just click on any value to trigger the callback that would handle the drilldown.  I believe he checked in the handler around 12/25.  

http://nicolas.kruchten.com/pivottable/examples/mps_prepop.html

**Comment by dave-killough** [comment]
Here's some background:
http://github.com/nicolaskruchten/pivottable/issues/33

**Comment by nagarajanchinnasamy** [comment]
Thanks. Just thinking if we should treat the click event on a sub-total cell different from a value cell? Any thoughts?

**Comment by dave-killough** [comment]
I think they should be treated the same way, passing in the filters behind the selected cell.  They're all subtotals to me.  That's why I like the drill-down.

**Comment by nagarajanchinnasamy** [comment]
@dave-killough I have committed the feature to master branch.

The syntax is slightly different from the original PivotTable.js package. Added an example of event handling to `examples/260_event_handlers.html`. Let me know if you have any thoughts on this.

Please check and provide your feedback.

**Comment by nagarajanchinnasamy** [comment]
Feature released. Closing the issue. Please report as a new issue if any...

**Comment by dave-killough** [comment]
Thank you very much - I will check this out when I get back to it.
