### ISSUE TITLE
Being able to hide subtotals columns when expanding.

### ISSUE THREAD

**Issue by Dams591** [nagarajanchinnasamy/pivottable-subtotal-renderer#26]
Hey  @nagarajanchinnasamy 

This time I'm trying to find the way to display subtotals columns only when collapsed. Once we expand I want to hide the subtotals column in order to see only the children. In the next example, Australia is expanded I therefore need to hide the subtotals columns (and values) highlighted in yellow.

Thanks ! 

![5060dec2-e19d-11e6-90d6-71d9e2c2aba5](https://cloud.githubusercontent.com/assets/12731716/22240138/fb4d6400-e219-11e6-8642-4dfe74840b18.png)

**Comment by nagarajanchinnasamy** [comment]
Hi @Dams591 I've started working on this. You can track the progress in `hide-on-expand` branch. **Work In Progress.**

I have added a `rendererOption` called `rowSubtotalDisplay: "HideOnExpand"` to indicate hiding of subtotal rows when expanded. Please check [270_hide_subtotal_on_expand.html](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/blob/hide-on-expand/examples/270_hide_subtotal_on_expand.html#L39) for an example.` **The work is not complete yet.** 

Similarly, I will be adding `colSubtotalDisplay: "HideOnExpand"` for hiding column subtotals when expanded.

Will need couple of weekends to complete. Hope that estimate helps you :)

**Comment by nagarajanchinnasamy** [comment]
You are welcome :)

Pure css only solution was possible for rows. But for columns I could not find a solution only with css.

Still trying to figure out a generic logic to make it work for both row-subtotal-hide-on-expand and col-subtotal-hide-on-expand options. One specific race-condition i need to resolve. Very close...but not there yet :)

**Comment by nagarajanchinnasamy** [comment]
@Dams591, both `rowSubtotalDisplay: "Hide On Expand"` and `colSubtotalDisplay: "Hide On Expand"` are added and committed to `hide-on-expand` branch. Pls note the spaces between the words in `"Hide On Expand"`

Following examples are added:
- examples/270_hide_subtotal_on_expand.html
- examples/273_hide_subtotal_on_expand.html
- examples/275_hide_subtotal_on_expand.html

Performance improvement and a bit of code clean up is pending.

Could you please check and let me know your feedback. Thanks :)

**Comment by Dams591** [comment]
Amazing ! Let me review your changes I'll give you my feedback ASAP. Thank you so much for being so reactive !

**Comment by nagarajanchinnasamy** [comment]
I have made more commits with bug fixes. Pls take the latest version. I will be making couple of more commits before I merge this with master branch.

**Comment by nagarajanchinnasamy** [comment]
Feature supported as part of release v1.7.1 (Pull request #28)

**Comment by Dams591** [comment]
@nagarajanchinnasamy I succesfully implemented it to my solution also made it compatible with multiple values. In case you are interested in having multiple values in your plugin one day check this out
http://codepen.io/anon/pen/YNVbJm?editors=0010 

Thank you for your help on this, let's keep sharing the good stuff ! I'm heading to the position of the row subtotals as we speak I'll let you know asap.

**Comment by nagarajanchinnasamy** [comment]
@Dams591 Glad to know you could integrate your solution. Hope it was easy :)

I am still thinking of a generic logic for (or trying to understand) multiple values feature.

All the best on positioning row-sub-totals #12 . Points to remember are:

1. Current logic makes use of row-span, which is always upper-row-to-lower-row expansion in HTML
2. Expand and Collapse operations affect the parent header's row-span values

So, the secret is in buildRowHeaders, collapseRow and expandRow functions :)
