### ISSUE TITLE
subtotal prototype undefined

### ISSUE THREAD

**Issue by KishanManali1824** [nagarajanchinnasamy/pivottable-subtotal-renderer#30]
Gettig an error while using subtotal.js in pivot() function.
Can not read property 'prototype' as undefined.

Please provide support for this.

![error](https://cloud.githubusercontent.com/assets/19813124/24292731/96db4cca-10b4-11e7-96c7-620bdddedae3.png)

**Comment by nagarajanchinnasamy** [comment]
Hi could you please share some sample code to reproduce the problem so that I understand what exactly is happening. Thanks.

**Comment by KishanManali1824** [comment]
Hi its solved.Its pivotjs file issue. Thanks for reply.
But now how can i hide row/column expand collapse to show subtotal
Please guide.
![demo1](https://cloud.githubusercontent.com/assets/19813124/24390610/abdc551a-13a7-11e7-9dd4-b0612dcda808.png)

**Comment by KishanManali1824** [comment]
Its solved.
Now help me how to hide expand collapse of rows & columns while showing
subtotal.

Thanks.

On Mar 28, 2017 5:00 AM, "Nagarajan Chinnasamy" <notifications@github.com>
wrote:

Hi could you please share some sample code to reproduce the problem so that
I understand what exactly is happening. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/issues/30#issuecomment-289616738>,
or mute the thread

**Comment by KishanManali1824** [comment]
Ok Please Check My Code Of Binding Pivot to Div Tag With SUbtotal.

 function pivotUi(id) {

        var dataClass = $.pivotUtilities.SubtotalPivotData;
        var derivers = $.pivotUtilities.derivers;
        var renderer = $.pivotUtilities.subtotal_renderers["Table With Subtotal"];

        var sum = $.pivotUtilities.aggregatorTemplates.sum;
        var numberFormat = $.pivotUtilities.numberFormat;
        var intFormat = numberFormat({ digitsAfterDecimal: 0 });

        $('#Pivot' + id).pivot($scope.Rpt_report, {
            dataClass: dataClass,
            rows: $scope.Rpt_rows,
            cols: $scope.Rpt_columns,
            aggregator: sum(intFormat)($scope.Rpt_data),
            renderer: renderer,
            rendererOptions: {
                colSubtotalDisplay: "disableExpandCollapse",
            }
        });
    }

Now How can i hide expand/collapse of rows column with subtotal.
Thanks.

**Comment by nagarajanchinnasamy** [comment]
Hi, Glad you could solve your issues. Please check following examples:

- [Hide Row and/or Column Subtotals On Expand](http://nagarajanchinnasamy.com/subtotal/examples/170_hide_subtotal_on_expand.html)
- [Disable Row and/or Column Subtotals](http://nagarajanchinnasamy.com/subtotal/examples/180_disable_subtotal.html)
- [Disable Expand Collapse Operations](http://nagarajanchinnasamy.com/subtotal/examples/185_disable_expandcollapse.html)

and let me know if your requirements are met. Thanks.

**Comment by KishanManali1824** [comment]
Hi, I have tried all options but not working.
Is there any changes in pivotjs file or not.
And what i want is to mentioned in attach demo files.
Please check & support.

Let me know.
Thanks.
![demo2](https://cloud.githubusercontent.com/assets/19813124/24439159/1ba0ee34-146a-11e7-9643-964c0e3ed759.png)
![demo4](https://cloud.githubusercontent.com/assets/19813124/24439160/1bb9c940-146a-11e7-972e-cf97d78242ed.png)

**Comment by nagarajanchinnasamy** [comment]
Hmmm... Interesting requirements :)

1. In the latest version, the way to use `rowSubtotalDisplay` and `colSubtotalDisplay` has changed. Please check examples.
2. To hide arrows, you can set `arrowCollapsed` and `arrowExpanded` to an empty string
3. Hiding subtotal selectively at a particular sub-level is not supported currently

**Comment by KishanManali1824** [comment]
Hi, I have checked all option.
Now i dont need to hide arrow button for expand collapse but
I really want to hide sublevel subtotal row-wise because in big reports its not showing perfectly.
Please check my attachment of sublevel subtotal.

If possible by any way i really need it to show subtotal just by first row wise not by its sub-level wise.

Waiting for positive reply.

Thanks.

![sublevel_problem](https://cloud.githubusercontent.com/assets/19813124/24488247/2c572cec-1533-11e7-870e-ad3474822be1.png)

**Comment by nagarajanchinnasamy** [comment]
Hi,

At present its not possible to show subtotal only at a specific level. I will take this as an enhancement. But may not be implemented immediately. Will take time.

**Comment by KishanManali1824** [comment]
Ok, i will wait for it but let me know can we set sub-level in collapeble mode by default.
If that possible then its gd for me.

Waiting for your reply.

Thanks.
