### ISSUE TITLE
Subtotal on Column

### ISSUE THREAD

**Issue by emcedeltate** [nagarajanchinnasamy/pivottable-subtotal-renderer#32]
First of all thank you for "subtotal.js". I have a question about subtotal on column.
I want to display "Totals" under the "NAK_YEM_KILO". How can i do this?

![2017-03-29_13h45_10](https://cloud.githubusercontent.com/assets/11711212/24451278/cd8a9ad4-1486-11e7-86e0-7294731849cb.png)

**Comment by nagarajanchinnasamy** [comment]
Hi Thanks. Sorry for the delayed response. I hope u managed to implement this. Possibly through  CSS + JavaScript!?

**Comment by nagarajanchinnasamy** [comment]
Closing as there is no response.
