### ISSUE TITLE
Disable subtotals under a specified level

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [nagarajanchinnasamy/pivottable-subtotal-renderer#33]
As discussed in #30 . See the image.
![1bb9c940-146a-11e7-972e-cf97d78242ed](https://cloud.githubusercontent.com/assets/1784880/24491609/bbb35278-1545-11e7-80c5-2e2d09461ac7.png)

**Comment by KishanManali1824** [comment]
Hello,

Is there any updates in this issue.
I am looking for this sub-total solution for my big project in Essar Steel, Surat.
Please provide support for this.

Thanks.

**Comment by KishanManali1824** [comment]
Hello Sir,

Please give any update in this issue.

Waiting for positive reply.

Thanks.

**Comment by zwirnerj** [comment]
Hi KishanManali1824,
just	to put in my two cents because I read your comments at morning in the subway... this famous peace of software is probably developed in sparetime and we get it for free. So in my opinion it is no good style to claim for support or ernhanced features. But for sure it is ok to make suggestions.
There is always the oportunity for you to enhance the code to your needs and to share that if think it is a useful enhancement.
Kind regrads
Jörg

**Comment by KishanManali1824** [comment]
Hello Sir

Sorry for that.I am not claiming for any support or enhancement.
I just need help or suggesting in this issue.

Thanks

**Comment by nagarajanchinnasamy** [comment]
Sorry...couldn't spend time on this yet. Will try to implement over this weekend if possible.

Thanks for your interest, feedback n support :)

**Comment by KishanManali1824** [comment]
Hello

OK. Will wait for positive reply.

Thanks for reply me back.

**Comment by nagarajanchinnasamy** [comment]
I plan to add a renderer option `hideAfter` under `rowSubtotalDisplay` and `colSubtotalDisplay` as shown in the following example:

    rowSubtotalDisplay: {
        hideAfter: 0
    }

`hideAfter` takes the position of an attribute in the attribute-hierarchy. This will hide the subtotal rows/cols from row header 1 onwards. I have one question and a thought regarding this.

- Should this also hide the header titles (Category and Dispatchability in the example image above)?
- In case of pivotUI, when users drag and drop row and column attributes, they will not have an option to change this configuration  (hideAfter value) based on the attribute hierarchy. So, this may not be a good option to be used in pivotUI. 

Your comments are welcome. Thanks.

**Comment by KishanManali1824** [comment]
Hello

Thanks for replying back.In my case i am not using pivotUI function.
I directly bind pivot using pivot function of your pivot.js without drag & drop.
For me its required to show the header titles after hiding sub-total of rows.

So, this is my suggestion & implement as your  way.

Thanks & waiting for positive reply.

**Comment by nagarajanchinnasamy** [comment]
@KishanManali1824  Am still not clear about this requirement.

If you don't want to show Category and Dispatchability, why don't you just exclude them from `rows` attributes list?

**Comment by nagarajanchinnasamy** [comment]
Sorry... I got it. :) You just want to hide the subtotals for them.

**Comment by KishanManali1824** [comment]
Hello

I want to hide their sub total & not the rows itself.

I think u got it.

Thanks & waiting for implementation.

**Comment by KishanManali1824** [comment]
Hi

Sorry to ping you but i want to know is there any updated in your current implementation?

Looking for support from your side.

Waiting for positive reply.

Thanks.
Kishan Kadam.

**Comment by nagarajanchinnasamy** [comment]
@KishanManali1824 and friends as you can see I have committed the implementation for this feature in [disable-after](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/tree/disable-after) branch.

[An example is provided here...](https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/blob/disable-after/examples/290_disable_after.html)

Please check and let me know if everything is fine.

**Comment by KishanManali1824** [comment]
Hello

Its great work sir.Working fine as per my solution.

Soo many thanks for it.You save me.

Thanks.

**Comment by nagarajanchinnasamy** [comment]
Implemented in Version 1.10.0
