### ISSUE TITLE
sub-total display problem

### ISSUE THREAD

**Issue by KishanManali1824** [nagarajanchinnasamy/pivottable-subtotal-renderer#35]
Respected 

I am looking for displaying subtotal of rows below the row.
Currently its showing above the rows but i need to show it below that particular row.

Please support.

Thanks
Kishan Kadam.
![demo2](https://cloud.githubusercontent.com/assets/19813124/25383049/ded4df28-29d7-11e7-831c-768718e1e52d.png)

**Comment by KishanManali1824** [comment]
Hello

Is there any for support in this issue. 
Please help to solve this issue.

Waiting for positive reply.

Thanks
Kishan Kadam.

**Comment by nagarajanchinnasamy** [comment]
Hi @KishanManali1824 , this is same as #12 

Let me know your views there.

**Comment by KishanManali1824** [comment]
Hi

I just tried to change function but nothing happning.

Please try to resolve this issue.

Thanks
