### ISSUE TITLE
Type Error: Cannot read property '' of undefined

### ISSUE THREAD

**Issue by rippi** [nagarajanchinnasamy/pivottable-subtotal-renderer#4]
When changing the renderer from one of the standard ones to 'Table with Subtotal' or any other of the subtotal renderers I get an exception.

```
TypeError: Cannot read property '' of undefined
    at buildValues (subtotal.coffee:262)
    at main (subtotal.coffee:600)
    at SubtotalRenderer (subtotal.coffee:622)
    at Object.Table With Subtotal [as renderer] (subtotal.coffee:625)
    at jQuery.$.fn.pivot (pivot.coffee:549)
    at pivot.coffee:852
```

at line 262 in subtotal.coffee:
`aggregator = tree[flatRowKey][flatColKey] ? {value: (-> null), format: -> ""}`
everything after the ? is getting marked red by Chrome DevTools

Not shure what went wrong there.

**Comment by nagarajanchinnasamy** [comment]
Hi, I modified the [PivotUI Example](http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivotui.html) to use Table renders with the following change:

        var renderers = $.extend($.pivotUtilities.renderers, 
            $.pivotUtilities.subtotal_renderers);

I could switch between renderers without any issue. if you can share some sample code to simulate the error, that will help me to diagnose the problem and fix it if any...

**Comment by rippi** [comment]
I'm doing exactly the same. The only difference is my data source. It's some JSON with part filled, part empty fields in it.
I tried it and this error comes up when there are empty fields in one of the column attributes.
Example JSON:
`[{"name":"Frank","age":"35","gender":"male"},{"name":"Lisa","age":"25","gender":"female"},{"name":"Tom","age":"","gender":"male"}]`
Put `gender `and `name `in rows and `age `in cols and select count as aggregator

**Comment by rippi** [comment]
Oh, I didn't get the newest Version of pivottable.js. 
Sorry for my stupidity ^-^
