### ISSUE TITLE
Subtotal heatmap colors

### ISSUE THREAD

**Issue by rmatusiak** [nagarajanchinnasamy/pivottable-subtotal-renderer#45]
Hi. I managed to provide my own color scale to PivotTable.js with the following code:

rendererOptions: {
     heatmap: {
          colorScaleGenerator: function(values) {
          return d3.scale.linear()
          .domain([0, 50, 100, 101])
          .range(["#83d0c9", "#65c3ba", "#009688", "#d9534f"])
           }
      }
},

However, the values in my subtotal rows are not coloured. Is the any solution for this?

**Comment by rmatusiak** [comment]
I resolved the issue by modifying SubTotal.css file. Below the answer:

.pvtRowSubtotal {
	/*background-color: #EFEFEF !important;*/
	font-weight:bold;
    }

    .pvtColSubtotal {
	/*background-color: #EFEFEF !important;*/
	font-weight:bold;
    }

**Comment by nagarajanchinnasamy** [comment]
Glad you could resolve it 👍
