### ISSUE TITLE
Getting subtotal for each and every level of a column.

### ISSUE THREAD

**Issue by WSAyan** [nagarajanchinnasamy/pivottable-subtotal-renderer#48]
Is there any way to calculate subtotal column wise. For example I have generated table like following screenshot , what i want to get here is to calculate the subtotal of each rows. 

![sub](https://user-images.githubusercontent.com/7785995/30595688-b881d320-9d73-11e7-9230-c97d258bac60.PNG)

**Comment by nagarajanchinnasamy** [comment]
Hi @WSAyan 

Thanks for your interest in Subtotal.js 👍 

This library provides support for both row-wise and column-wise subtotal. Have you checked the [examples here](http://nagarajanchinnasamy.com/subtotal/).

Please explain your requirement using one of the examples. So that I am able to understand your requirement better.

**Comment by WSAyan** [comment]
Sorry for the unclear question. I was a bit confused about what I want. I am trying to ad calculated column fields based on user calculation. So far I've  been able to calculate percentage of **C _WEALTH_RANK_A** based on **G_WEALTH_RANK_TOTAL** as you can see them on following screenshot. And the calculation works fine but the problem is when Subtotal.js calculating all the values according to its attributes (eg: sum,integer sum,count) . So I guess what I need is to get subtotal values of a column in each and every level so that I can calculate another calculated column field based on those subtotal values.
![sub2](https://user-images.githubusercontent.com/7785995/30691858-0323a71e-9eeb-11e7-8aca-50285c00c9e6.PNG)

PS: I am changing the name of the issue as it is irrelevant to the topic. Again sorry for such a stupid question.

**Comment by nagarajanchinnasamy** [comment]
@WSAyan Thanks for the explanation. If I understood your requirement correct, I think, its same as issue: #41 (Aggregator on the subtotal only)[https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/issues/41).

Please confirm my understanding is correct or not.

**Comment by WSAyan** [comment]
Yes it is pretty much same issue. Thanks a lot. 👍
