### ISSUE TITLE
Fill color or bold for sub totals

### ISSUE THREAD

**Issue by ahmad003** [nagarajanchinnasamy/pivottable-subtotal-renderer#6]
Is there a way to fill subtotals with color or bold the text ?

**Comment by nagarajanchinnasamy** [comment]
The `<td>` elements of subtotals are created with class `pvtVal pvtColSubtotal pvtRowSubtotal`. Could you please use CSS to style them?

**Comment by nagarajanchinnasamy** [comment]
For E.g., I tried the following code to style them dynamically as follows:

    $(".pvtRowSubtotal").css("background-color", "#EFEFEF")
    $(".pvtColSubtotal").css("background-color", "#EFEFEF")

Just to color the background.

**Comment by nagarajanchinnasamy** [comment]
[Please check example: Pivot() With Subtotal Row And Column Styling - Bold Text and Background Color #EFEFEF](http://nagarajanchinnasamy.com/subtotal/examples/subtotal_pivot_css.html)
