### ISSUE TITLE
Cannot collapse any rows in multi-index pivot table.

### ISSUE THREAD

**Issue by jake6192** [nagarajanchinnasamy/pivottable-subtotal-renderer#65]
I have created a table with 2 row values and 3 column values - the columns are collapsible but the rows are not.
I have tried initially with just the 'pivot' method, now moved to 'pivotUI' method but no difference.

![image](https://user-images.githubusercontent.com/26007329/52776447-825e5480-3039-11e9-9000-a35d146eef06.png)

So the Year & Month columns work as expected, but the Router Revision does not - the icon will change, but all child rows seem to stay visible? Nothing logged to the console either.

![image](https://user-images.githubusercontent.com/26007329/52776645-f7318e80-3039-11e9-940e-388a5b269db7.png)

Ideally i would like to be able to toggle to display of the subtotals for this particular table, but my team needs to be able to have the expand/collapse functionality here _(I am fairly certain this is currently not possible without subtotal.js)_. I guess that the only way to hide subtotals at the moment is with CSS?

```html
<script src="libs/jquery-3.3.1.js"></script>
<script src="libs/jquery-ui.js"></script>
<script src="libs/pivot.js"></script>
<script src="libs/subtotal.js"></script>
```

```javascript
var dataClass = $.pivotUtilities.SubtotalPivotData;
var renderers = $.pivotUtilities.subtotal_renderers;

$("#mainContainer").html('').pivotUI(_DATA_, {
    dataClass: dataClass,
    renderers: renderers,
    rendererName: "Table With Subtotal",
    rows: ["Router Revision", "Room Number"],
    cols: ["Year", "Month", "Day"],
    vals: ["Bit Count"],
    aggregatorName: "Integer Sum"
});
```

Still trying to get my head around some parts, but i think i'm doing this right.. Please correct me if i'm wrong. Am i possibly missing a library or two? These rows just refuse to collapse no matter what i try!

**Comment by tschroedertlc** [comment]
I'm also having the same issue and I am also new to using this library. @jake6192 Did you ever solve this problem? Thanks!

**Comment by tschroedertlc** [comment]
Figured it out finally. My issue was that I did not add the link for subtotal.min.css, which is a vital part of displaying everything correctly.

**Comment by jake6192** [comment]
I ended up coding it myself haha, but good to know i missed a much easier fix... Cheers :)

**Comment by nagarajanchinnasamy** [comment]
adding the link for subtotal.min.css resolved the issue.
