### ISSUE TITLE
Multiple tables on same page interfers with each other

### ISSUE THREAD

**Issue by kjeldahl** [nagarajanchinnasamy/pivottable-subtotal-renderer#8]
When multiple pivot tables are on the same page columns are expanded on all tables when expanding in one.

The reason is that setColVisibility (https://github.com/nagarajanchinnasamy/pivottable-subtotal-renderer/blob/master/subtotal.coffee#L303) is not scoped to the current table.

**Comment by nagarajanchinnasamy** [comment]
@kjeldahl Thanks for your contribution. I will merge your pull request.
